/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:3486f6fe-e103-46c8-8352-f1152a1b31d0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_FWlsRVBp3",
    "aws_user_pools_web_client_id": "3nfp9e3m6s3842ushir89fftq9",
    "oauth": {}
};


export default awsmobile;
